module.exports = [{
    id: 1,
    name: 'Bulbasaur',
    attack: undefined,
    defense: 49,
    type: 'grass',
    moves: ['tackle', 'vine whip'],
    curve: 1.3,
    levels: [5, 10],
    probability: 3,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 2,
    name: 'Ivysaur',
    attack: undefined,
    defense: 63,
    type: 'grass',
    moves: ['tackle', 'vine whip', 'razor leaf'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 3,
    name: 'Venusaur',
    attack: undefined,
    defense: 83,
    type: 'grass',
    moves: ['tackle', 'vine whip', 'razor leaf'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 4,
    name: 'Charmander',
    attack: undefined,
    defense: 43,
    type: 'fire',
    moves: ['scratch', 'ember', 'metal claw'],
    curve: 1.3,
    levels: [5, 10],
    probability: 3,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 5,
    name: 'Charmeleon',
    attack: undefined,
    defense: 58,
    type: 'fire',
    moves: ['scratch', 'ember', 'metal claw', 'flamethrower'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 6,
    name: 'Charizard',
    attack: undefined,
    defense: 78,
    type: 'fire',
    moves: ['flamethrower', 'wing attack', 'slash', 'metal claw'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 7,
    name: 'Squirtle',
    attack: undefined,
    defense: 65,
    type: 'water',
    moves: ['tackle', 'bubble', 'water gun'],
    curve: 1.3,
    levels: [5, 10],
    probability: 3,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 8,
    name: 'Wartortle',
    attack: undefined,
    defense: 80,
    type: 'water',
    moves: ['tackle', 'bubble', 'water gun', 'bite'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 9,
    name: 'Blastoise',
    attack: undefined,
    defense: 100,
    type: 'water',
    moves: ['hydro pump', 'bubble', 'water gun', 'bite'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 10,
    name: 'Caterpie',
    attack: undefined,
    defense: 35,
    type: 'bug',
    moves: ['tackle'],
    curve: 1.6,
    levels: [2, 7],
    probability: 15,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 11,
    name: 'Butterfree',
    attack: undefined,
    defense: 50,
    type: 'bug',
    moves: ['confusion', 'gust', 'psybeam', 'silver wind'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 12,
    name: 'Weedle',
    attack: undefined,
    defense: 30,
    type: 'bug',
    moves: ['poison sting'],
    curve: 1.6,
    levels: [2, 7],
    probability: 15,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 13,
    name: 'Pidgey',
    attack: undefined,
    defense: 40,
    type: 'normal',
    moves: ['tackle', 'gust'],
    curve: 1.3,
    levels: [2, 10],
    probability: 15,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 14,
    name: 'Pidgeotto',
    attack: undefined,
    defense: 55,
    type: 'normal',
    moves: ['tackle', 'gust', 'wing attack'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 15,
    name: 'Pidgeot',
    attack: undefined,
    defense: 75,
    type: 'normal',
    moves: ['tackle', 'gust', 'wing attack'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 16,
    name: 'Rattata',
    attack: undefined,
    defense: 35,
    type: 'normal',
    moves: ['tackle', 'hyper fang'],
    curve: 1.6,
    levels: [2, 7],
    probability: 20,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 17,
    name: 'Raticate',
    attack: undefined,
    defense: 60,
    type: 'normal',
    moves: ['tackle', 'hyper fang'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 18,
    name: 'Spearow',
    attack: undefined,
    defense: 30,
    type: 'normal',
    moves: ['peck'],
    curve: 1.6,
    levels: [5, 15],
    probability: 10,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 19,
    name: 'Fearow',
    attack: undefined,
    defense: 65,
    type: 'normal',
    moves: ['peck', 'drill peck'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 20,
    name: 'Ekans',
    attack: undefined,
    defense: 44,
    type: 'poison',
    moves: ['poison sting', 'bite'],
    curve: 1.6,
    levels: [5, 15],
    probability: 15,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 21,
    name: 'Arbok',
    attack: undefined,
    defense: 69,
    type: 'poison',
    moves: ['poison sting', 'bite', 'acid'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 22,
    name: 'Raichu',
    attack: undefined,
    defense: 55,
    type: 'electric',
    moves: ['thundershock', 'thunderbolt'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 23,
    name: 'Sandshrew',
    attack: undefined,
    defense: 85,
    type: 'ground',
    moves: ['scratch', 'poison sting'],
    curve: 1.6,
    levels: [5, 15],
    probability: 10,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 24,
    name: 'Sandslash',
    attack: undefined,
    defense: 110,
    type: 'ground',
    moves: ['scratch', 'poison sting', 'slash', 'swift'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 25,
    name: 'Nidoran',
    attack: undefined,
    defense: 52,
    type: 'poison',
    moves: ['scratch'],
    curve: 1.3,
    levels: [5, 8],
    probability: 15,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 26,
    name: 'Nidoqueen',
    attack: undefined,
    defense: 87,
    type: 'poison',
    moves: ['scratch', 'poison sting', 'body slam', 'superpower'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 27,
    name: 'Nidoran',
    attack: undefined,
    defense: 40,
    type: 'poison',
    moves: ['peck'],
    curve: 1.3,
    levels: [5, 8],
    probability: 15,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 28,
    name: 'Nidoking',
    attack: undefined,
    defense: 77,
    type: 'poison',
    moves: ['peck', 'poison sting', 'megahorn'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 29,
    name: 'Ninetales',
    attack: undefined,
    defense: 75,
    type: 'fire',
    moves: ['ember'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 30,
    name: 'Zubat',
    attack: undefined,
    defense: 35,
    type: 'poison',
    moves: ['astonish', 'bite', 'wing attack'],
    curve: 1.6,
    levels: [5, 15],
    probability: 15,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 31,
    name: 'Golbat',
    attack: undefined,
    defense: 70,
    type: 'poison',
    moves: ['poison fang', 'bite', 'wing attack', 'air cutter'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 32,
    name: 'Paras',
    attack: undefined,
    defense: 55,
    type: 'bug',
    moves: ['scratch'],
    curve: 1.6,
    levels: [5, 15],
    probability: 15,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 33,
    name: 'Parasect',
    attack: undefined,
    defense: 80,
    type: 'bug',
    moves: ['scratch', 'slash'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 34,
    name: 'Venonat',
    attack: undefined,
    defense: 50,
    type: 'bug',
    moves: ['tackle', 'confusion'],
    curve: 1.6,
    levels: [10, 24],
    probability: 8,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 35,
    name: 'Venomoth',
    attack: undefined,
    defense: 60,
    type: 'bug',
    moves: ['psybeam', 'psychic', 'confusion', 'gust'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 36,
    name: 'Diglett',
    attack: undefined,
    defense: 25,
    type: 'ground',
    moves: ['scratch'],
    curve: 1.6,
    levels: [8, 16],
    probability: 15,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 37,
    name: 'Dugtrio',
    attack: undefined,
    defense: 50,
    type: 'ground',
    moves: ['scratch', 'slash', 'earthquake'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 38,
    name: 'Meowth',
    attack: undefined,
    defense: 35,
    type: 'normal',
    moves: ['scratch', 'bite'],
    curve: 1.6,
    levels: [8, 20],
    probability: 10,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 39,
    name: 'Persian',
    attack: undefined,
    defense: 60,
    type: 'normal',
    moves: ['scratch', 'bite', 'slash'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 40,
    name: 'Psyduck',
    attack: undefined,
    defense: 48,
    type: 'water',
    moves: ['scratch', 'confusion'],
    curve: 1.6,
    levels: [8, 20],
    probability: 15,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 41,
    name: 'Golduck',
    attack: undefined,
    defense: 78,
    type: 'water',
    moves: ['scratch', 'confusion', 'hydro pump'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 42,
    name: 'Mankey',
    attack: undefined,
    defense: 35,
    type: 'fighting',
    moves: ['scratch', 'low kick', 'karate chop'],
    curve: 1.6,
    levels: [5, 18],
    probability: 8,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 43,
    name: 'Primeape',
    attack: undefined,
    defense: 60,
    type: 'fighting',
    moves: ['scratch', 'low kick', 'karate chop', 'cross chop'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 44,
    name: 'Arcanine',
    attack: undefined,
    defense: 80,
    type: 'fire',
    moves: ['bite', 'ember'],
    curve: 1,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 45,
    name: 'Poliwag',
    attack: undefined,
    defense: 40,
    type: 'water',
    moves: ['bubble', 'water gun'],
    curve: 1.3,
    levels: [5, 18],
    probability: 6,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 46,
    name: 'Poliwrath',
    attack: undefined,
    defense: 95,
    type: 'water',
    moves: ['water gun'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 47,
    name: 'Alakazam',
    attack: undefined,
    defense: 45,
    type: 'psychic',
    moves: ['confusion', 'psybeam', 'psychic'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 48,
    name: 'Machop',
    attack: undefined,
    defense: 50,
    type: 'fighting',
    moves: ['low kick', 'karate chop'],
    curve: 1.3,
    levels: [5, 19],
    probability: 12,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 49,
    name: 'Machamp',
    attack: undefined,
    defense: 80,
    type: 'fighting',
    moves: ['low kick', 'karate chop', 'cross chop', 'dynamicpunch'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 50,
    name: 'Bellsprout',
    attack: undefined,
    defense: 35,
    type: 'grass',
    moves: ['vine whip'],
    curve: 1.3,
    levels: [5, 20],
    probability: 15,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 51,
    name: 'Victreebel',
    attack: undefined,
    defense: 65,
    type: 'grass',
    moves: ['vine whip', 'razor leaf'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 52,
    name: 'Tentacool',
    attack: undefined,
    defense: 35,
    type: 'water',
    moves: ['poison sting', 'constrict', 'acid', 'bubblebeam'],
    curve: 1,
    levels: [5, 20],
    probability: 10,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 53,
    name: 'Tentacruel',
    attack: undefined,
    defense: 65,
    type: 'water',
    moves: ['hydro pump', 'constrict', 'acid', 'bubblebeam'],
    curve: 1,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 54,
    name: 'Geodude',
    attack: undefined,
    defense: 100,
    type: 'rock',
    moves: ['tackle', 'rock throw'],
    curve: 1.3,
    levels: [5, 20],
    probability: 15,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 55,
    name: 'Golem',
    attack: undefined,
    defense: 130,
    type: 'rock',
    moves: ['tackle', 'rock throw', 'earthquake'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 56,
    name: 'Ponyta',
    attack: undefined,
    defense: 55,
    type: 'fire',
    moves: ['ember', 'stomp'],
    curve: 1.6,
    levels: [20, 35],
    probability: 6,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 57,
    name: 'Rapidash',
    attack: undefined,
    defense: 70,
    type: 'fire',
    moves: ['ember', 'stomp', 'fire blast'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 58,
    name: 'Slowpoke',
    attack: undefined,
    defense: 65,
    type: 'water',
    moves: ['tackle', 'water gun', 'confusion', 'headbutt'],
    curve: 1.6,
    levels: [25, 35],
    probability: 5,
    favorite: false,
    received: true,
    deleted: false
  }, {
    id: 59,
    name: 'Slowbro',
    attack: undefined,
    defense: 110,
    type: 'water',
    moves: ['psychic', 'water gun', 'confusion', 'headbutt'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 60,
    name: 'Magnemite',
    attack: undefined,
    defense: 70,
    type: 'electric',
    moves: ['tackle', 'thundershock', 'spark'],
    curve: 1.6,
    levels: [5, 20],
    probability: 8,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 61,
    name: 'Magneton',
    attack: undefined,
    defense: 95,
    type: 'electric',
    moves: ['tackle', 'thundershock', 'spark', 'zap cannon'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 62,
    name: 'Farfetch\'d',
    attack: undefined,
    defense: 55,
    type: 'normal',
    moves: ['peck', 'slash'],
    curve: 1.6,
    levels: [25, 40],
    probability: 8,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 63,
    name: 'Doduo',
    attack: undefined,
    defense: 45,
    type: 'normal',
    moves: ['peck'],
    curve: 1.6,
    levels: [15, 25],
    probability: 8,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 64,
    name: 'Dodrio',
    attack: undefined,
    defense: 70,
    type: 'normal',
    moves: ['peck', 'drill peck'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 65,
    name: 'Seel',
    attack: undefined,
    defense: 55,
    type: 'water',
    moves: ['headbutt', 'icy wind', 'aurora beam'],
    curve: 1.6,
    levels: [25, 30],
    probability: 4,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 66,
    name: 'Dewgong',
    attack: undefined,
    defense: 80,
    type: 'water',
    moves: ['ice beam', 'headbutt', 'icy wind', 'aurora beam'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 67,
    name: 'Grimer',
    attack: undefined,
    defense: 50,
    type: 'poison',
    moves: ['pound', 'sludge'],
    curve: 1.6,
    levels: [5, 30],
    probability: 10,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 68,
    name: 'Muk',
    attack: undefined,
    defense: 75,
    type: 'poison',
    moves: ['pound', 'sludge', 'sludge bomb'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 69,
    name: 'Cloyster',
    attack: undefined,
    defense: 180,
    type: 'water',
    moves: ['aurora beam'],
    curve: 1,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 70,
    name: 'Gastly',
    attack: undefined,
    defense: 30,
    type: 'ghost',
    moves: ['tackle', 'lick'],
    curve: 1.3,
    levels: [5, 15],
    probability: 10,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 71,
    name: 'Gengar',
    attack: undefined,
    defense: 60,
    type: 'ghost',
    moves: ['tackle', 'lick', 'shadow punch', 'shadow ball'],
    curve: 1.3,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 72,
    name: 'Onix',
    attack: undefined,
    defense: 160,
    type: 'rock',
    moves: ['iron tail', 'rock throw', 'dragonbreath', 'slam'],
    curve: 1.6,
    levels: [5, 40],
    probability: 8,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 73,
    name: 'Drowzee',
    attack: undefined,
    defense: 45,
    type: 'psychic',
    moves: ['pound', 'confusion', 'headbutt'],
    curve: 1.6,
    levels: [5, 15],
    probability: 8,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 74,
    name: 'Hypno',
    attack: undefined,
    defense: 70,
    type: 'psychic',
    moves: ['pound', 'confusion', 'headbutt', 'psychic'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 75,
    name: 'Krabby',
    attack: undefined,
    defense: 90,
    type: 'water',
    moves: ['bubble', 'vicegrip', 'mud shot', 'stomp'],
    curve: 1.6,
    levels: [15, 20],
    probability: 6,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 76,
    name: 'Kingler',
    attack: undefined,
    defense: 115,
    type: 'water',
    moves: ['stomp', 'crabhammer', 'vicegrip', 'mud shot'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 77,
    name: 'Voltorb',
    attack: undefined,
    defense: 50,
    type: 'electric',
    moves: ['tackle', 'spark'],
    curve: 1.6,
    levels: [5, 12],
    probability: 6,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 78,
    name: 'Electrode',
    attack: undefined,
    defense: 70,
    type: 'electric',
    moves: ['tackle', 'spark', 'swift'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 79,
    name: 'Exeggutor',
    attack: undefined,
    defense: 85,
    type: 'grass',
    moves: ['confusion', 'stomp', 'egg bomb'],
    curve: 1,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 80,
    name: 'Cubone',
    attack: undefined,
    defense: 95,
    type: 'ground',
    moves: ['bone club', 'headbutt'],
    curve: 1.6,
    levels: [15, 22],
    probability: 5,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 81,
    name: 'Marowak',
    attack: undefined,
    defense: 110,
    type: 'ground',
    moves: ['bone club', 'headbutt'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 82,
    name: 'Hitmonlee',
    attack: undefined,
    defense: 53,
    type: 'fighting',
    moves: ['rolling kick'],
    curve: 1.6,
    levels: [5, 15],
    probability: 4,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 83,
    name: 'Hitmonchan',
    attack: undefined,
    defense: 79,
    type: 'fighting',
    moves: ['mega punch', 'ice punch', 'fire punch', 'sky uppercut'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 84,
    name: 'Lickitung',
    attack: undefined,
    defense: 75,
    type: 'normal',
    moves: ['lick', 'stomp', 'slam'],
    curve: 1.6,
    levels: [5, 15],
    probability: 10,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 85,
    name: 'Koffing',
    attack: undefined,
    defense: 95,
    type: 'poison',
    moves: ['tackle', 'smog', 'sludge'],
    curve: 1.6,
    levels: [15, 25],
    probability: 6,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 86,
    name: 'Weezing',
    attack: undefined,
    defense: 120,
    type: 'poison',
    moves: ['tackle', 'smog', 'sludge'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 87,
    name: 'Rhyhorn',
    attack: undefined,
    defense: 95,
    type: 'ground',
    moves: ['horn attack', 'stomp'],
    curve: 1,
    levels: [15, 35],
    probability: 4,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 88,
    name: 'Rhydon',
    attack: undefined,
    defense: 120,
    type: 'ground',
    moves: ['horn attack', 'stomp', 'earthquake', 'megahorn'],
    curve: 1,
    levels: undefined,
    probability: undefined,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 89,
    name: 'Chansey',
    attack: undefined,
    defense: 5,
    type: 'normal',
    moves: ['pound', 'egg bomb'],
    curve: 1.9,
    levels: [25, 55],
    probability: 4,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 90,
    name: 'Tangela',
    attack: undefined,
    defense: 115,
    type: 'grass',
    moves: ['constrict', 'vine whip', 'slam'],
    curve: 1.6,
    levels: [15, 45],
    probability: 4,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 91,
    name: 'Kangaskhan',
    attack: undefined,
    defense: 80,
    type: 'normal',
    moves: ['bite', 'mega punch', 'dizzy punch'],
    curve: 1.6,
    levels: [5, 45],
    probability: 4,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 92,
    name: 'Horsea',
    attack: undefined,
    defense: 70,
    type: 'water',
    moves: ['bubble', 'water gun', 'twister'],
    curve: 1.6,
    levels: [5, 15],
    probability: 10,
    favorite: false,
    received: false,
    deleted: true
  }, {
    id: 93,
    name: 'Seadra',
    attack: undefined,
    defense: 95,
    type: 'water',
    moves: ['bubble', 'water gun', 'twister', 'hydro pump'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 94,
    name: 'Goldeen',
    attack: undefined,
    defense: 60,
    type: 'water',
    moves: ['peck', 'horn attack'],
    curve: 1.6,
    levels: [5, 25],
    probability: 12,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 95,
    name: 'Seaking',
    attack: undefined,
    defense: 65,
    type: 'water',
    moves: ['peck', 'horn attack', 'waterfall', 'megahorn'],
    curve: 1.6,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 96,
    name: 'Starmie',
    attack: undefined,
    defense: 85,
    type: 'water',
    moves: ['water gun', 'swift'],
    curve: 1,
    levels: undefined,
    probability: undefined,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 97,
    name: 'Mr. mime',
    attack: undefined,
    defense: 65,
    type: 'psychic',
    moves: ['confusion', 'magical leaf', 'psybeam', 'psychic'],
    curve: 1.6,
    levels: [5, 15],
    probability: 4,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 98,
    name: 'Scyther',
    attack: undefined,
    defense: 80,
    type: 'bug',
    moves: ['wing attack', 'slash'],
    curve: 1.6,
    levels: [5, 15],
    probability: 4,
    favorite: true,
    received: false,
    deleted: false
  }, {
    id: 99,
    name: 'Jynx',
    attack: undefined,
    defense: 35,
    type: 'ice',
    moves: ['body slam', 'blizzard', 'powder snow', 'ice punch'],
    curve: 1.6,
    levels: [5, 15],
    probability: 4,
    favorite: true,
    received: false,
    deleted: false
  },

  {
    id: 100,
    "name": "Electabuzz",
    "attack": 83,
    "defense": 57,
    "type": "electric",
    "moves": ["thunderpunch", "swift", "thunderbolt", "thunder"],
    "curve": 1.6,
    "levels": [5, 15],
    "probability": 4,

    "favorite": false,
    "received": false,
    "deleted": false

  },
  {

    id: 101,
    "name": "Magmar",
    "attack": 95,
    "defense": 57,
    "type": "fire",
    "moves": ["fire blast", "smog", "fire punch", "flamethrower"],
    "curve": 1.6,
    "levels": [5, 15],
    "probability": 4,

    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 102,
    "name": "Pinsir",
    "attack": 125,
    "defense": 10,
    "type": "bug",
    "moves": ["vicegrip"],
    "curve": 1,
    "levels": [5, 15],
    "probability": 4,

    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 103,
    "name": "Tauros",
    "attack": 10,
    "defense": 95,
    "type": "normal",
    "moves": ["tackle", "horn attack"],
    "curve": 1,
    "levels": [5, 15],
    "probability": 4,


    "favorite": true,
    "received": false,
    "deleted": false
  },
  {
    id: 104,
    "name": "Magikarp",
    "attack": 1,
    "defense": 55,
    "evolveLevel": 2,
    "evolveTo": "13",
    "type": "water",
    "moves": ["tackle"],
    "curve": 1,
    "levels": [5, 15],
    "probability": 15,

    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 105,
    "name": "Gyarados",
    "attack": 125,
    "defense": 79,
    "type": "water",
    "moves": ["bite", "twister", "hydro pump"],
    "curve": 1,

    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 106,
    "name": "Lapras",
    "attack": 85,
    "defense": 8,
    "type": "water",
    "moves": ["water gun", "body slam", "ice beam", "hydro pump"],
    "curve": 1,
    "levels": [5, 15],
    "probability": 4,

    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 107,
    "name": "Eevee",
    "attack": 55,
    "defense": 5,
    "type": "normal",
    "moves": ["tackle", "bite"],
    "curve": 1.6,
    "levels": [5, 35],
    "probability": 8,


    "favorite": true,
    "received": false,
    "deleted": false


  },
  {
    id: 108,
    "name": "Jolteon",
    "levels": [5, 15],
    "probability": 4,
    "attack": 65,
    "defense": 6,
    "type": "electric",
    "moves": ["tackle", "thundershock", "thunder"],
    "curve": 1.6,


    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 109,
    "name": "Flareon",
    "attack": 13,
    "defense": 6,
    "type": "fire",
    "moves": ["flamethrower", "ember", "bite", "smog"],
    "curve": 1.6,

    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 110,
    "name": "Porygon",
    "attack": 6,
    "defense": 7,
    "type": "normal",
    "moves": ["tackle", "psybeam", "zap cannon"],
    "curve": 1.6,
    "levels": [5, 45],
    "probability": 4,

    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 111,
    "name": "Omanyte",
    "attack": 4,
    "defense": 10,
    "evolveLevel": 4,
    "evolveTo": "139",
    "type": "rock",
    "moves": ["constrict", "bite", "water gun", "mud shot"],
    "curve": 1.6,

    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 112,
    "name": "Omastar",
    "attack": 6,
    "defense": 125,
    "type": "rock",
    "moves": ["ancientpower", "hydro pump", "water gun", "mud shot"],
    "curve": 1.6,

    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 113,
    "name": "Kabuto",
    "attack": 8,
    "defense": 9,
    "evolveLevel": 4,
    "evolveTo": "141",
    "type": "rock",
    "moves": ["scratch", "mud shot"],
    "curve": 1.6,


    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 114,
    "name": "Kabutops",
    "attack": 115,
    "defense": 15,
    "type": "rock",
    "moves": ["scratch", "mud shot", "slash", "ancientpower"],
    "curve": 1.6,


    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 115,
    "name": "Aerodactyl",
    "attack": 15,
    "defense": 65,
    "type": "rock",
    "moves": ["wing attack", "bite", "ancientpower"],
    "curve": 1,


    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 116,
    "name": "Snorlax",
    "attack": 11,
    "defense": 65,
    "type": "normal",
    "moves": ["tackle", "headbutt", "snore", "body slam"],
    "curve": 1,
    "levels": [25, 25],
    "probability": 2,

    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 117,
    "name": "Articuno",
    "attack": 85,
    "defense": 10,
    "type": "ice",
    "moves": ["gust", "powder snow", "ice beam", "blizzard"],
    "curve": 1,
    "levels": [5, 50],
    "probability": 1,

    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 118,
    "name": "Zapdos",
    "attack": 9,
    "defense": 85,
    "type": "electric",
    "moves": ["peck", "thundershock", "drill peck", "thunder"],
    "curve": 1,
    "levels": [5, 50],
    "probability": 1,


    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 119,
    "name": "Moltres",
    "attack": 10,
    "defense": 9,
    "type": "fire",
    "moves": ["wing attack", "ember", "flamethrower", "heat wave"],
    "curve": 1,
    "levels": [5, 50],
    "probability": 1,


    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 129,
    "name": "Dratini",
    "attack": 64,
    "defense": 45,
    "evolveLevel": 3,
    "evolveTo": "148",
    "type": "dragon",
    "moves": ["twister", "slam"],
    "curve": 1,
    "levels": [1, 20],
    "probability": 6,


    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 130,
    "name": "Dragonair",
    "attack": 84,
    "defense": 65,
    "evolveLevel": 55,
    "evolveTo": "149",
    "type": "dragon",
    "moves": ["twister", "slam"],
    "curve": 1,



    "favorite": true,
    "received": false,
    "deleted": false
  },
  {
    id: 131,
    "name": "Dragonite",
    "attack": 134,
    "defense": 95,
    "type": "dragon",
    "moves": ["twister", "slam", "wing attack"],
    "curve": 1,



    "favorite": true,
    "received": false,
    "deleted": false
  },
  {
    id: 132,
    "name": "Mewtwo",
    "attack": 11,
    "defense": 9,
    "type": "psychic",
    "moves": ["confusion", "swift", "psychic"],
    "curve": 1,
    "levels": [7, 70],
    "probability": 1,

    "favorite": true,
    "received": false,
    "deleted": false

  },
  {
    id: 133,
    "name": "Mew",
    "attack": 10,
    "defense": 10,
    "type": "psychic",
    "moves": ["pound", "mega punch", "psychic", "ancientpower"],
    "curve": 1.3,
    "levels": [5, 50],
    "probability": .3,

    "favorite": true,
    "received": false,
    "deleted": false
  }
];
